apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-api-config
  namespace: devops
data:
  SPRING_PROFILES_ACTIVE: "default"
  SERVER_PORT: "8080"
  LOG_LEVEL: "INFO"
  SPRING_JPA_OPEN_IN_VIEW: "false"
  APP_NAME: "employee-api"
